// Btaudio
syntax = "proto3";

message ConnectedPeer {
    string          devicename = 1;
    string          macaddr = 2;
    bool            asksforconnection = 3;
}

message BluetoothAudioMessage {
    bool            btc = 1;  // bluetooth connection status
    bool            btp = 2;  // bluetooth play status
    string          bts = 3;  // bluetooth song title
    string          bta = 4;  // bluetooth artist
    uint32          btd = 5;  // bluetooth duration
    uint32          btpos = 6;  // bluetooth position
    float           btsv = 7;  // bluetooth volume
    uint32          playstatus = 8;
    optional        ConnectedPeer connectedpeer = 9;
    uint32          ck = 100; // check data
}

message BluetoothAudioControlMessage {
    bool            btp = 1;  // play
    bool            btpa = 2;  // pause
    bool            btpn = 3;  // next
    bool            btpb = 4;  // back
    float           btsv = 6;  // volume value
    bool            btsm = 7;  // mute
    bool            btpair = 8;  // pair
    bool            btdisconnect = 9;
    bool            fastforward = 10;
    bool            rewind = 11;
    bool            discoverable = 12;
    bool            pincodeactive = 13;
    bool            confirmconnection = 14;
    bool            rejectconnection = 15;
    uint32          pincode = 16;


    uint32          ck = 100; // check data
}