syntax = "proto3";

message Joystick {
    sint32          x = 1;
    sint32          y = 2;
    bool            btn = 3;
}

message DPad {
    bool            up = 1;
    bool            down = 2;
    bool            left = 3;
    bool            right = 4;
}

message RemotecontrolMessage {
    sint32          leftX = 1;  // left joystick x
    sint32          leftY = 2;  // left joystick y
    sint32          rightX = 3;  // right joystick x
    sint32          rightY = 4;  // right joystick y
    bool            btnA = 5;  // button A
    bool            btnB = 6;  // button B
    bool            btnX = 7;  // button X
    bool            btnY = 8;  // button Y
    bool            btnL = 9;  // button L
    bool            btnR = 10;  // button R
    bool            btnZL = 11;  // button ZL
    bool            btnZR = 12;  // button ZR
    bool            btnPlus = 13;  // button Plus
    bool            btnMinus = 14;  // button Minus
    bool            btnHome = 15;  // button Home
    bool            btnO = 16;  // button O
    bool            btnT = 17;  // button T
    bool            btndpadup = 18;  // dpad up
    bool            btndpaddown = 19;  // dpad down
    bool            btndpadleft = 20;  // dpad left
    bool            btndpadright = 21;  // dpad right

    bool            btnLStick = 22;  // button LStick
    bool            btnRStick = 23;  // button RStick
    Joystick        leftJoystick = 24;  // left joystick	
    Joystick        rightJoystick = 25;  // right joystick
    DPad            dpad = 26;  // dpad         
    bool            connected = 98;  // controller connection status
    int32           battery = 99;
    uint32          ck = 100; // check data
}