/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "btaudio.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ConnectedPeer, ConnectedPeer, AUTO)


PB_BIND(BluetoothAudioMessage, BluetoothAudioMessage, 2)


PB_BIND(BluetoothAudioControlMessage, BluetoothAudioControlMessage, 2)



