/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DISPLAY_PB_H_INCLUDED
#define PB_DISPLAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DisplayMessage {
    char dummy_field;
} DisplayMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DisplayMessage_init_default              {0}
#define DisplayMessage_init_zero                 {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
#define DisplayMessage_FIELDLIST(X, a) \

#define DisplayMessage_CALLBACK NULL
#define DisplayMessage_DEFAULT NULL

extern const pb_msgdesc_t DisplayMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DisplayMessage_fields &DisplayMessage_msg

/* Maximum encoded size of messages (where known) */
#define DISPLAY_PB_H_MAX_SIZE                    DisplayMessage_size
#define DisplayMessage_size                      0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
