/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_KISC_PB_H_INCLUDED
#define PB_KISC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RemotecontrolMessage {
    char dummy_field;
} RemotecontrolMessage;

typedef struct _BluetoothAudioMessage {
    bool btc; /* bluetooth connection status */
    bool btp; /* bluetooth play status */
    pb_callback_t bts; /* bluetooth song title */
    pb_callback_t bta; /* bluetooth artist */
    uint32_t btd; /* bluetooth duration */
    uint32_t btpos; /* bluetooth position */
    float btsv; /* bluetooth volume */
    uint32_t ck; /* check data */
} BluetoothAudioMessage;

typedef struct _BluetoothAudioControlMessage {
    bool btp; /* play */
    bool btpa; /* pause */
    bool btpn; /* next */
    bool btpb; /* back */
    float btsv; /* volume value */
    bool btsm; /* mute */
    bool btpair; /* pair */
    uint32_t ck; /* check data */
} BluetoothAudioControlMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RemotecontrolMessage_init_default        {0}
#define BluetoothAudioMessage_init_default       {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0}
#define BluetoothAudioControlMessage_init_default {0, 0, 0, 0, 0, 0, 0, 0}
#define RemotecontrolMessage_init_zero           {0}
#define BluetoothAudioMessage_init_zero          {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0}
#define BluetoothAudioControlMessage_init_zero   {0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BluetoothAudioMessage_btc_tag            1
#define BluetoothAudioMessage_btp_tag            2
#define BluetoothAudioMessage_bts_tag            3
#define BluetoothAudioMessage_bta_tag            4
#define BluetoothAudioMessage_btd_tag            5
#define BluetoothAudioMessage_btpos_tag          6
#define BluetoothAudioMessage_btsv_tag           7
#define BluetoothAudioMessage_ck_tag             100
#define BluetoothAudioControlMessage_btp_tag     1
#define BluetoothAudioControlMessage_btpa_tag    2
#define BluetoothAudioControlMessage_btpn_tag    3
#define BluetoothAudioControlMessage_btpb_tag    4
#define BluetoothAudioControlMessage_btsv_tag    6
#define BluetoothAudioControlMessage_btsm_tag    7
#define BluetoothAudioControlMessage_btpair_tag  8
#define BluetoothAudioControlMessage_ck_tag      100

/* Struct field encoding specification for nanopb */
#define RemotecontrolMessage_FIELDLIST(X, a) \

#define RemotecontrolMessage_CALLBACK NULL
#define RemotecontrolMessage_DEFAULT NULL

#define BluetoothAudioMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     btc,               1) \
X(a, STATIC,   SINGULAR, BOOL,     btp,               2) \
X(a, CALLBACK, SINGULAR, STRING,   bts,               3) \
X(a, CALLBACK, SINGULAR, STRING,   bta,               4) \
X(a, STATIC,   SINGULAR, UINT32,   btd,               5) \
X(a, STATIC,   SINGULAR, UINT32,   btpos,             6) \
X(a, STATIC,   SINGULAR, FLOAT,    btsv,              7) \
X(a, STATIC,   SINGULAR, UINT32,   ck,              100)
#define BluetoothAudioMessage_CALLBACK pb_default_field_callback
#define BluetoothAudioMessage_DEFAULT NULL

#define BluetoothAudioControlMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     btp,               1) \
X(a, STATIC,   SINGULAR, BOOL,     btpa,              2) \
X(a, STATIC,   SINGULAR, BOOL,     btpn,              3) \
X(a, STATIC,   SINGULAR, BOOL,     btpb,              4) \
X(a, STATIC,   SINGULAR, FLOAT,    btsv,              6) \
X(a, STATIC,   SINGULAR, BOOL,     btsm,              7) \
X(a, STATIC,   SINGULAR, BOOL,     btpair,            8) \
X(a, STATIC,   SINGULAR, UINT32,   ck,              100)
#define BluetoothAudioControlMessage_CALLBACK NULL
#define BluetoothAudioControlMessage_DEFAULT NULL

extern const pb_msgdesc_t RemotecontrolMessage_msg;
extern const pb_msgdesc_t BluetoothAudioMessage_msg;
extern const pb_msgdesc_t BluetoothAudioControlMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RemotecontrolMessage_fields &RemotecontrolMessage_msg
#define BluetoothAudioMessage_fields &BluetoothAudioMessage_msg
#define BluetoothAudioControlMessage_fields &BluetoothAudioControlMessage_msg

/* Maximum encoded size of messages (where known) */
/* BluetoothAudioMessage_size depends on runtime parameters */
#define BluetoothAudioControlMessage_size        24
#define KISC_PB_H_MAX_SIZE                       BluetoothAudioControlMessage_size
#define RemotecontrolMessage_size                0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
