/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_KISC_PB_H_INCLUDED
#define PB_KISC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RemotecontrolMessage {
    int32_t ax; /* left stick x position */
    int32_t ay; /* left stick y position */
    int32_t az; /* right stick z position */
    int32_t aw; /* right stick w position */
    int32_t bA; /* buttonA data */
    int32_t bB; /* buttonB data */
    int32_t bX; /* buttonX data */
    int32_t bY; /* buttonY data */
    int32_t bL; /* buttonL data */
    int32_t bR; /* buttonR data */
    int32_t bU; /* buttonUp data */
    int32_t bD; /* buttonDown data */
    uint32_t btl; /* battery level */
    int32_t ck; /* check data */
} RemotecontrolMessage;

typedef struct _BluetoothAudioMessage {
    uint32_t btl; /* battery level */
    float btv; /* battery voltage */
    int32_t x; /* x position */
    int32_t y; /* y position */
    int32_t z; /* z position */
    bool e1; /* event1 data */
    bool e2; /* event2 data */
    bool e3; /* event3 data */
    float t1; /* variable1 data */
    float t2; /* variable2 data */
    uint32_t ck; /* check data */
} BluetoothAudioMessage;

typedef struct _BluetoothAudioControlMessage {
    uint32_t ck; /* check data */
} BluetoothAudioControlMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RemotecontrolMessage_init_default        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BluetoothAudioMessage_init_default       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BluetoothAudioControlMessage_init_default {0}
#define RemotecontrolMessage_init_zero           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BluetoothAudioMessage_init_zero          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BluetoothAudioControlMessage_init_zero   {0}

/* Field tags (for use in manual encoding/decoding) */
#define RemotecontrolMessage_ax_tag              1
#define RemotecontrolMessage_ay_tag              2
#define RemotecontrolMessage_az_tag              3
#define RemotecontrolMessage_aw_tag              4
#define RemotecontrolMessage_bA_tag              5
#define RemotecontrolMessage_bB_tag              6
#define RemotecontrolMessage_bX_tag              7
#define RemotecontrolMessage_bY_tag              8
#define RemotecontrolMessage_bL_tag              9
#define RemotecontrolMessage_bR_tag              10
#define RemotecontrolMessage_bU_tag              11
#define RemotecontrolMessage_bD_tag              12
#define RemotecontrolMessage_btl_tag             13
#define RemotecontrolMessage_ck_tag              14
#define BluetoothAudioMessage_btl_tag            1
#define BluetoothAudioMessage_btv_tag            2
#define BluetoothAudioMessage_x_tag              3
#define BluetoothAudioMessage_y_tag              4
#define BluetoothAudioMessage_z_tag              5
#define BluetoothAudioMessage_e1_tag             6
#define BluetoothAudioMessage_e2_tag             7
#define BluetoothAudioMessage_e3_tag             8
#define BluetoothAudioMessage_t1_tag             9
#define BluetoothAudioMessage_t2_tag             10
#define BluetoothAudioMessage_ck_tag             11
#define BluetoothAudioControlMessage_ck_tag      100

/* Struct field encoding specification for nanopb */
#define RemotecontrolMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, SINT32,   ax,                1) \
X(a, STATIC,   REQUIRED, SINT32,   ay,                2) \
X(a, STATIC,   REQUIRED, SINT32,   az,                3) \
X(a, STATIC,   REQUIRED, SINT32,   aw,                4) \
X(a, STATIC,   REQUIRED, INT32,    bA,                5) \
X(a, STATIC,   REQUIRED, INT32,    bB,                6) \
X(a, STATIC,   REQUIRED, INT32,    bX,                7) \
X(a, STATIC,   REQUIRED, INT32,    bY,                8) \
X(a, STATIC,   REQUIRED, INT32,    bL,                9) \
X(a, STATIC,   REQUIRED, INT32,    bR,               10) \
X(a, STATIC,   REQUIRED, INT32,    bU,               11) \
X(a, STATIC,   REQUIRED, INT32,    bD,               12) \
X(a, STATIC,   REQUIRED, UINT32,   btl,              13) \
X(a, STATIC,   REQUIRED, INT32,    ck,               14)
#define RemotecontrolMessage_CALLBACK NULL
#define RemotecontrolMessage_DEFAULT NULL

#define BluetoothAudioMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   btl,               1) \
X(a, STATIC,   REQUIRED, FLOAT,    btv,               2) \
X(a, STATIC,   REQUIRED, SINT32,   x,                 3) \
X(a, STATIC,   REQUIRED, SINT32,   y,                 4) \
X(a, STATIC,   REQUIRED, SINT32,   z,                 5) \
X(a, STATIC,   REQUIRED, BOOL,     e1,                6) \
X(a, STATIC,   REQUIRED, BOOL,     e2,                7) \
X(a, STATIC,   REQUIRED, BOOL,     e3,                8) \
X(a, STATIC,   REQUIRED, FLOAT,    t1,                9) \
X(a, STATIC,   REQUIRED, FLOAT,    t2,               10) \
X(a, STATIC,   REQUIRED, UINT32,   ck,               11)
#define BluetoothAudioMessage_CALLBACK NULL
#define BluetoothAudioMessage_DEFAULT NULL

#define BluetoothAudioControlMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   ck,              100)
#define BluetoothAudioControlMessage_CALLBACK NULL
#define BluetoothAudioControlMessage_DEFAULT NULL

extern const pb_msgdesc_t RemotecontrolMessage_msg;
extern const pb_msgdesc_t BluetoothAudioMessage_msg;
extern const pb_msgdesc_t BluetoothAudioControlMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RemotecontrolMessage_fields &RemotecontrolMessage_msg
#define BluetoothAudioMessage_fields &BluetoothAudioMessage_msg
#define BluetoothAudioControlMessage_fields &BluetoothAudioControlMessage_msg

/* Maximum encoded size of messages (where known) */
#define BluetoothAudioControlMessage_size        7
#define BluetoothAudioMessage_size               51
#define KISC_PB_H_MAX_SIZE                       RemotecontrolMessage_size
#define RemotecontrolMessage_size                129

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
