/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_KISC_PB_H_INCLUDED
#define PB_KISC_PB_H_INCLUDED
#include <pb.h>
#include "system.pb.h"
#include "light.pb.h"
#include "motor.pb.h"
#include "btaudio.pb.h"
#include "soundgenerator.pb.h"
#include "remotecontrol.pb.h"
#include "display.pb.h"
#include "peripherals.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
