/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "motor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MotorControl, MotorControl, AUTO)


PB_BIND(MotorFeedback, MotorFeedback, AUTO)


PB_BIND(MotorboardControl, MotorboardControl, AUTO)


PB_BIND(MotorboardFeedback, MotorboardFeedback, 2)



