/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PERIPHERALS_PB_H_INCLUDED
#define PB_PERIPHERALS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PeripheralsFeedbackMessage {
    char dummy_field;
} PeripheralsFeedbackMessage;

typedef struct _PeripheralsControlMessage {
    char dummy_field;
} PeripheralsControlMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PeripheralsFeedbackMessage_init_default  {0}
#define PeripheralsControlMessage_init_default   {0}
#define PeripheralsFeedbackMessage_init_zero     {0}
#define PeripheralsControlMessage_init_zero      {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
#define PeripheralsFeedbackMessage_FIELDLIST(X, a) \

#define PeripheralsFeedbackMessage_CALLBACK NULL
#define PeripheralsFeedbackMessage_DEFAULT NULL

#define PeripheralsControlMessage_FIELDLIST(X, a) \

#define PeripheralsControlMessage_CALLBACK NULL
#define PeripheralsControlMessage_DEFAULT NULL

extern const pb_msgdesc_t PeripheralsFeedbackMessage_msg;
extern const pb_msgdesc_t PeripheralsControlMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PeripheralsFeedbackMessage_fields &PeripheralsFeedbackMessage_msg
#define PeripheralsControlMessage_fields &PeripheralsControlMessage_msg

/* Maximum encoded size of messages (where known) */
#define PERIPHERALS_PB_H_MAX_SIZE                PeripheralsFeedbackMessage_size
#define PeripheralsControlMessage_size           0
#define PeripheralsFeedbackMessage_size          0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
