/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "peripherals.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PedalMessage, PedalMessage, AUTO)


PB_BIND(RFIDMessage, RFIDMessage, AUTO)


PB_BIND(RotaryEncoderMessage, RotaryEncoderMessage, AUTO)


PB_BIND(PeripheralsFeedbackMessage, PeripheralsFeedbackMessage, AUTO)


PB_BIND(PeripheralsControlMessage, PeripheralsControlMessage, AUTO)



