/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "remotecontrol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Joystick, Joystick, AUTO)


PB_BIND(DPad, DPad, AUTO)


PB_BIND(Rumble, Rumble, AUTO)


PB_BIND(Accelerometer, Accelerometer, AUTO)


PB_BIND(Gyroscope, Gyroscope, AUTO)


PB_BIND(RemotecontrolMessage, RemotecontrolMessage, 2)



