/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_REMOTECONTROL_PB_H_INCLUDED
#define PB_REMOTECONTROL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Joystick {
    int32_t x;
    int32_t y;
    bool btn;
} Joystick;

typedef struct _RemotecontrolMessage {
    int32_t leftX; /* left joystick x */
    int32_t leftY; /* left joystick y */
    int32_t rightX; /* right joystick x */
    int32_t rightY; /* right joystick y */
    bool btnA; /* button A */
    bool btnB; /* button B */
    bool btnX; /* button X */
    bool btnY; /* button Y */
    bool btnL; /* button L */
    bool btnR; /* button R */
    bool btnZL; /* button ZL */
    bool btnZR; /* button ZR */
    bool btnPlus; /* button Plus */
    bool btnMinus; /* button Minus */
    bool btnHome; /* button Home */
    bool btnO; /* button O */
    bool btnT; /* button T */
    bool btndpadup; /* dpad up */
    bool btndpaddown; /* dpad down */
    bool btndpadleft; /* dpad left */
    bool btndpadright; /* dpad right */
    bool btnLStick; /* button LStick */
    bool btnRStick; /* button RStick */
    bool connected; /* controller connection status */
    int32_t battery;
    uint32_t ck; /* check data */
} RemotecontrolMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Joystick_init_default                    {0, 0, 0}
#define RemotecontrolMessage_init_default        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Joystick_init_zero                       {0, 0, 0}
#define RemotecontrolMessage_init_zero           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Joystick_x_tag                           1
#define Joystick_y_tag                           2
#define Joystick_btn_tag                         3
#define RemotecontrolMessage_leftX_tag           1
#define RemotecontrolMessage_leftY_tag           2
#define RemotecontrolMessage_rightX_tag          3
#define RemotecontrolMessage_rightY_tag          4
#define RemotecontrolMessage_btnA_tag            5
#define RemotecontrolMessage_btnB_tag            6
#define RemotecontrolMessage_btnX_tag            7
#define RemotecontrolMessage_btnY_tag            8
#define RemotecontrolMessage_btnL_tag            9
#define RemotecontrolMessage_btnR_tag            10
#define RemotecontrolMessage_btnZL_tag           11
#define RemotecontrolMessage_btnZR_tag           12
#define RemotecontrolMessage_btnPlus_tag         13
#define RemotecontrolMessage_btnMinus_tag        14
#define RemotecontrolMessage_btnHome_tag         15
#define RemotecontrolMessage_btnO_tag            16
#define RemotecontrolMessage_btnT_tag            17
#define RemotecontrolMessage_btndpadup_tag       18
#define RemotecontrolMessage_btndpaddown_tag     19
#define RemotecontrolMessage_btndpadleft_tag     20
#define RemotecontrolMessage_btndpadright_tag    21
#define RemotecontrolMessage_btnLStick_tag       22
#define RemotecontrolMessage_btnRStick_tag       23
#define RemotecontrolMessage_connected_tag       98
#define RemotecontrolMessage_battery_tag         99
#define RemotecontrolMessage_ck_tag              100

/* Struct field encoding specification for nanopb */
#define Joystick_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, SINT32,   y,                 2) \
X(a, STATIC,   SINGULAR, BOOL,     btn,               3)
#define Joystick_CALLBACK NULL
#define Joystick_DEFAULT NULL

#define RemotecontrolMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   leftX,             1) \
X(a, STATIC,   SINGULAR, SINT32,   leftY,             2) \
X(a, STATIC,   SINGULAR, SINT32,   rightX,            3) \
X(a, STATIC,   SINGULAR, SINT32,   rightY,            4) \
X(a, STATIC,   SINGULAR, BOOL,     btnA,              5) \
X(a, STATIC,   SINGULAR, BOOL,     btnB,              6) \
X(a, STATIC,   SINGULAR, BOOL,     btnX,              7) \
X(a, STATIC,   SINGULAR, BOOL,     btnY,              8) \
X(a, STATIC,   SINGULAR, BOOL,     btnL,              9) \
X(a, STATIC,   SINGULAR, BOOL,     btnR,             10) \
X(a, STATIC,   SINGULAR, BOOL,     btnZL,            11) \
X(a, STATIC,   SINGULAR, BOOL,     btnZR,            12) \
X(a, STATIC,   SINGULAR, BOOL,     btnPlus,          13) \
X(a, STATIC,   SINGULAR, BOOL,     btnMinus,         14) \
X(a, STATIC,   SINGULAR, BOOL,     btnHome,          15) \
X(a, STATIC,   SINGULAR, BOOL,     btnO,             16) \
X(a, STATIC,   SINGULAR, BOOL,     btnT,             17) \
X(a, STATIC,   SINGULAR, BOOL,     btndpadup,        18) \
X(a, STATIC,   SINGULAR, BOOL,     btndpaddown,      19) \
X(a, STATIC,   SINGULAR, BOOL,     btndpadleft,      20) \
X(a, STATIC,   SINGULAR, BOOL,     btndpadright,     21) \
X(a, STATIC,   SINGULAR, BOOL,     btnLStick,        22) \
X(a, STATIC,   SINGULAR, BOOL,     btnRStick,        23) \
X(a, STATIC,   SINGULAR, BOOL,     connected,        98) \
X(a, STATIC,   SINGULAR, INT32,    battery,          99) \
X(a, STATIC,   SINGULAR, UINT32,   ck,              100)
#define RemotecontrolMessage_CALLBACK NULL
#define RemotecontrolMessage_DEFAULT NULL

extern const pb_msgdesc_t Joystick_msg;
extern const pb_msgdesc_t RemotecontrolMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Joystick_fields &Joystick_msg
#define RemotecontrolMessage_fields &RemotecontrolMessage_msg

/* Maximum encoded size of messages (where known) */
#define Joystick_size                            14
#define REMOTECONTROL_PB_H_MAX_SIZE              RemotecontrolMessage_size
#define RemotecontrolMessage_size                92

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
