/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SYSTEM_PB_H_INCLUDED
#define PB_SYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MemberType {
    MemberType_UNKNOWN = 0
} MemberType;

/* Struct definitions */
typedef struct _Heartbeat {
    uint32_t timestamp;
    uint32_t uptime;
    uint32_t ck; /* check data */
} Heartbeat;

typedef struct _Sysinfo {
    MemberType type;
    pb_callback_t name;
    pb_callback_t version;
    pb_callback_t ip;
    pb_callback_t mac;
    pb_callback_t ssid;
    pb_callback_t rssi;
    pb_callback_t uptime;
    pb_callback_t freeheap;
    pb_callback_t voltage;
    pb_callback_t temperature;
    pb_callback_t cpufreq;
    pb_callback_t flashsize;
    pb_callback_t flashspeed;
    pb_callback_t flashmode;
    pb_callback_t flashsizeid;
    pb_callback_t core;
    pb_callback_t sdk;
    pb_callback_t bootmode;
    pb_callback_t bootversion;
    pb_callback_t bootmode1;
    pb_callback_t bootversion1;
    uint32_t ck; /* check data */
} Sysinfo;

typedef struct _SysCommand {
    uint32_t command;
    uint32_t ck; /* check data */
} SysCommand;

typedef struct _SysMessage {
    bool has_heartbeat;
    Heartbeat heartbeat;
    bool has_info;
    Sysinfo info;
    bool has_command;
    SysCommand command;
    uint32_t ck; /* check data */
} SysMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MemberType_MIN MemberType_UNKNOWN
#define _MemberType_MAX MemberType_UNKNOWN
#define _MemberType_ARRAYSIZE ((MemberType)(MemberType_UNKNOWN+1))


#define Sysinfo_type_ENUMTYPE MemberType




/* Initializer values for message structs */
#define Heartbeat_init_default                   {0, 0, 0}
#define Sysinfo_init_default                     {_MemberType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define SysCommand_init_default                  {0, 0}
#define SysMessage_init_default                  {false, Heartbeat_init_default, false, Sysinfo_init_default, false, SysCommand_init_default, 0}
#define Heartbeat_init_zero                      {0, 0, 0}
#define Sysinfo_init_zero                        {_MemberType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define SysCommand_init_zero                     {0, 0}
#define SysMessage_init_zero                     {false, Heartbeat_init_zero, false, Sysinfo_init_zero, false, SysCommand_init_zero, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Heartbeat_timestamp_tag                  1
#define Heartbeat_uptime_tag                     2
#define Heartbeat_ck_tag                         100
#define Sysinfo_type_tag                         1
#define Sysinfo_name_tag                         2
#define Sysinfo_version_tag                      3
#define Sysinfo_ip_tag                           4
#define Sysinfo_mac_tag                          5
#define Sysinfo_ssid_tag                         6
#define Sysinfo_rssi_tag                         7
#define Sysinfo_uptime_tag                       8
#define Sysinfo_freeheap_tag                     9
#define Sysinfo_voltage_tag                      10
#define Sysinfo_temperature_tag                  11
#define Sysinfo_cpufreq_tag                      12
#define Sysinfo_flashsize_tag                    13
#define Sysinfo_flashspeed_tag                   14
#define Sysinfo_flashmode_tag                    15
#define Sysinfo_flashsizeid_tag                  16
#define Sysinfo_core_tag                         17
#define Sysinfo_sdk_tag                          18
#define Sysinfo_bootmode_tag                     19
#define Sysinfo_bootversion_tag                  20
#define Sysinfo_bootmode1_tag                    21
#define Sysinfo_bootversion1_tag                 22
#define Sysinfo_ck_tag                           100
#define SysCommand_command_tag                   1
#define SysCommand_ck_tag                        100
#define SysMessage_heartbeat_tag                 1
#define SysMessage_info_tag                      2
#define SysMessage_command_tag                   3
#define SysMessage_ck_tag                        100

/* Struct field encoding specification for nanopb */
#define Heartbeat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   uptime,            2) \
X(a, STATIC,   SINGULAR, UINT32,   ck,              100)
#define Heartbeat_CALLBACK NULL
#define Heartbeat_DEFAULT NULL

#define Sysinfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, SINGULAR, STRING,   version,           3) \
X(a, CALLBACK, SINGULAR, STRING,   ip,                4) \
X(a, CALLBACK, SINGULAR, STRING,   mac,               5) \
X(a, CALLBACK, SINGULAR, STRING,   ssid,              6) \
X(a, CALLBACK, SINGULAR, STRING,   rssi,              7) \
X(a, CALLBACK, SINGULAR, STRING,   uptime,            8) \
X(a, CALLBACK, SINGULAR, STRING,   freeheap,          9) \
X(a, CALLBACK, SINGULAR, STRING,   voltage,          10) \
X(a, CALLBACK, SINGULAR, STRING,   temperature,      11) \
X(a, CALLBACK, SINGULAR, STRING,   cpufreq,          12) \
X(a, CALLBACK, SINGULAR, STRING,   flashsize,        13) \
X(a, CALLBACK, SINGULAR, STRING,   flashspeed,       14) \
X(a, CALLBACK, SINGULAR, STRING,   flashmode,        15) \
X(a, CALLBACK, SINGULAR, STRING,   flashsizeid,      16) \
X(a, CALLBACK, SINGULAR, STRING,   core,             17) \
X(a, CALLBACK, SINGULAR, STRING,   sdk,              18) \
X(a, CALLBACK, SINGULAR, STRING,   bootmode,         19) \
X(a, CALLBACK, SINGULAR, STRING,   bootversion,      20) \
X(a, CALLBACK, SINGULAR, STRING,   bootmode1,        21) \
X(a, CALLBACK, SINGULAR, STRING,   bootversion1,     22) \
X(a, STATIC,   SINGULAR, UINT32,   ck,              100)
#define Sysinfo_CALLBACK pb_default_field_callback
#define Sysinfo_DEFAULT NULL

#define SysCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   command,           1) \
X(a, STATIC,   SINGULAR, UINT32,   ck,              100)
#define SysCommand_CALLBACK NULL
#define SysCommand_DEFAULT NULL

#define SysMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  heartbeat,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  info,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           3) \
X(a, STATIC,   SINGULAR, UINT32,   ck,              100)
#define SysMessage_CALLBACK NULL
#define SysMessage_DEFAULT NULL
#define SysMessage_heartbeat_MSGTYPE Heartbeat
#define SysMessage_info_MSGTYPE Sysinfo
#define SysMessage_command_MSGTYPE SysCommand

extern const pb_msgdesc_t Heartbeat_msg;
extern const pb_msgdesc_t Sysinfo_msg;
extern const pb_msgdesc_t SysCommand_msg;
extern const pb_msgdesc_t SysMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Heartbeat_fields &Heartbeat_msg
#define Sysinfo_fields &Sysinfo_msg
#define SysCommand_fields &SysCommand_msg
#define SysMessage_fields &SysMessage_msg

/* Maximum encoded size of messages (where known) */
/* Sysinfo_size depends on runtime parameters */
/* SysMessage_size depends on runtime parameters */
#define Heartbeat_size                           19
#define SYSTEM_PB_H_MAX_SIZE                     Heartbeat_size
#define SysCommand_size                          13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
