/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Heartbeat, Heartbeat, 2)


PB_BIND(Sysinfo, Sysinfo, 2)


PB_BIND(SysCommand, SysCommand, 2)


PB_BIND(SysMessage, SysMessage, 2)





